version: "3"  

tasks:  
  default: 
    cmds:  
      - task: generate  
  generate_go:  
    aliases: 
      - gen_go  
    desc: "Generate Go code from proto files" 
    cmds:
      - protoc -I proto proto/sso/*.proto --go_out=./gen/go/ --go_opt=paths=source_relative --go-grpc_out=./gen/go/ --go-grpc_opt=paths=source_relative
  generate_py:  
    aliases: 
      - gen_py  
    desc: "Generate Python code from proto files"  
    cmds:
      - python -m grpc_tools.protoc -I proto --python_out=./gen/python --grpc_python_out=./gen/python proto/sso/*.proto